version: "3.8"

services:
  robotagent:
    build:
      context: .
      dockerfile: Dockerfile
    image: robotagent:latest
    volumes:
      - ../mcp:/app/mcp
    working_dir: /app/mcp
    environment:
      - TZ=UTC
      - PYBULLET_STREAM_DIR=/app/mcp/.sim_stream
    tty: true
    ports:
      - "8001:8000"
    command: ["python", "mcp_server.py"]
