version: "3.8"

services:
  robotagent:
    build:
      context: .
      dockerfile: Dockerfile
    image: robotagent:latest
    volumes:
      - ../mcp:/app/mcp
    working_dir: /app
    environment:
      - TZ=UTC
    tty: true
