llm:
  chat: 'gpt-oss-20b-mlx'
  analysis: 'gpt-oss-20b-mlx'
  simulation: 'gpt-oss-20b-mlx'
  summary: 'qwen3-1.7b-mlx'
  tool_selector: 'qwen3-0.6b-mlx'
  judge: 'gpt-oss-20b-mlx'

model_url: "http://localhost:1234/v1"

mcp:
  ip: "http://localhost"
  port: "8001"