llm:
  chat: 'lmstudio-community:qwen3-4b-instruct-2507-mlx'
  analysis: 'lmstudio-community:qwen3-4b-instruct-2507-mlx'
  simulation: 'lmstudio-community:qwen3-4b-instruct-2507-mlx'
  summary: 'qwen3-1.7b-mlx'
  tool_selector: 'qwen3-0.6b-mlx'
  judge: 'lmstudio-community:qwen3-4b-instruct-2507-mlx'

model_url: "http://localhost:1234/v1"

mcp:
  ip: "http://localhost"
  port: "8001"